Citizen.CreateThread(function()
    -- PLANES
    AddTextEntry('JET', 'Boeing 747-8i')
    AddTextEntry('AN225', 'Antonov An-225 Mriya')
    AddTextEntry('A319', 'Airbus A319')
    AddTextEntry('A320', 'Airbus a320')
    AddTextEntry('A321', 'Airbus A321')
    AddTextEntry('a350x', 'Airbus A350xlr')
    AddTextEntry('a380', 'Airbus A380-800')
    AddTextEntry('aa10', 'Fairchild Republic A-10 Thunderbold')
    AddTextEntry('ac130', 'Lockheed AC-130')
    AddTextEntry('an32', 'Antonov An-32')
    AddTextEntry('b25', 'B-25 Mitchell')
    AddTextEntry('b707', 'Boeing 707')
    AddTextEntry('b757', 'Boeing 757')
    AddTextEntry('c130', 'Lockheed C-130 Hercules')
    AddTextEntry('c208', 'Cessna 208 Caravan')
    AddTextEntry('GLOBE', 'C-17 Globemaster')
    AddTextEntry('c172', 'Cessna C-172')
    AddTextEntry('GALAXY', 'C-5 Galaxy')
    AddTextEntry('conc', 'BAe Systems Concorde')
    AddTextEntry('crj700', 'Bombardier CRJ-700')
    AddTextEntry('dc10', 'Mcdonell douglas DC-10')
    AddTextEntry('e145', 'Embraer E-145')
    AddTextEntry('e175', 'Embraer E-175')
    AddTextEntry('e190', 'Embraer E-190')
    AddTextEntry('e390', 'Enbraer E-390')
    AddTextEntry('eurot', 'Eurofighter Typhoon')
    AddTextEntry('f16', 'F-16 Flying Falcon')
    AddTextEntry('f22a', 'Lockheed F22 Raptor')
    AddTextEntry('f35b', 'Lockheed F35 Lightning')
    AddTextEntry('f117', 'Lockheed F117 Nighthawk')
    AddTextEntry('fa18f', 'McDonnell Douglas F/A-18 Hornet')
    AddTextEntry('f50', 'Fokker 50')
    AddTextEntry('NINEF', 'Flying Mini')
    AddTextEntry('asw15', 'Glider')
    AddTextEntry('gripen', 'Gripen')
    AddTextEntry('heliplane', 'Chonky Carbobob')
    AddTextEntry('il76', 'Ilyushin Il-76')
    AddTextEntry('il96', 'Ilyushin Il-96')
    AddTextEntry('j10', 'Chengdu J-10')
    AddTextEntry('j31b', 'Chengdu J-31b')
    AddTextEntry('kj2000', 'KJ-2000')
    AddTextEntry('BLIMP', 'Hindenburg')
    AddTextEntry('mig21', 'MiG 21')
    AddTextEntry('mig31', 'MiG 31')
    AddTextEntry('mq9', 'MQ9 Drone')
    AddTextEntry('p8a', 'Boeing P-8 Posidon')
    -- AddTextEntry('b2s', '')
    AddTextEntry('spirit', 'B-2 Spirit')
    AddTextEntry('u2s', 'Lockheed U-2')
    AddTextEntry('sr71', 'Blackbird')
    -- HELICOPTERS
    AddTextEntry('LONGBOW', 'Boeing AH-64 Apache')
    -- CARS
    AddTextEntry('amggtbs', 'Mercedes AMG-GT')
    AddTextEntry('atom', 'Ariel Atom')
    AddTextEntry('rs6avant20', 'Audi RS6')
    AddTextEntry('760li06', 'BMW-760li')
    AddTextEntry('bmwm8', 'BMW M8')
    AddTextEntry('M5', 'BMW M5')
    AddTextEntry('x5mcompetition', 'BMW M5X')
    AddTextEntry('bolide', 'Bugatti Bolide')
    AddTextEntry('CHIRON17', 'Bugatti Chiron')
    AddTextEntry('c8r', 'Corvetter C8')
    AddTextEntry('cr500', 'Caterham R500')
    AddTextEntry('corvette63', 'Corvette C63')
    AddTextEntry('DEMON', 'Dodge Charger Demon')
    AddTextEntry('TESTAROSSA', 'Ferrari Testarossa')
    AddTextEntry('C39', '')
    AddTextEntry('indif1', 'F1 IndyCar')
    AddTextEntry('F40VANS', 'Ferrari F40')
    AddTextEntry('ferrari_pista_spider', '')
    AddTextEntry('sf90', 'Ferrari SF90')
    AddTextEntry('ffrs', 'Ford Focus RS')
    AddTextEntry('gle21', 'Mercedes GLE-21')
    AddTextEntry('gtr50', 'Nissan GTR-50')
    AddTextEntry('hondelsol', 'Honda Del-Sol')
    AddTextEntry('HurPerNov', 'Lamborghini Huracan Peformante')
    AddTextEntry('jag13', 'Jaguar')
    AddTextEntry('STO', '')
    AddTextEntry('SIANR', 'Lamborghini Sian Roadster')
    AddTextEntry('oyclc500', 'Lexus LC-2000')
    AddTextEntry('sc300', 'Lexus SC-300')
    AddTextEntry('ligier_lmp2', 'Ligier_LMP2')
    AddTextEntry('lotus11', 'F1-Lotus')
    AddTextEntry('hypersport', 'Lykan Hypersport')
    AddTextEntry('720nlargo', 'McLaren 720')
    AddTextEntry('mcgt20', 'McLaren GT')
    AddTextEntry('mercedesf1', 'F1-Mercedes')
    AddTextEntry('AMGCE', 'Mercedes AMG-CE')
    AddTextEntry('g63', 'Mercedes G63')
    AddTextEntry('sl65bs', 'Mercedes SL65')
    AddTextEntry('RTRUCK', 'Mercedes Racing Truck')
    AddTextEntry('multipla', 'Fiat Multipla')
    -- AddTextEntry('mads14', '')
    AddTextEntry('bnr32', 'Nissan BNR-32')
    AddTextEntry('TOPCAR911', 'Porsche 911 Topcar')
    AddTextEntry('NSPEEDO', 'PedoVan')
    AddTextEntry('30082021', 'Puogeot')
    AddTextEntry('por718gt4', 'Porsche 718')
    AddTextEntry('REDBULL', 'F1-Redbull')
    AddTextEntry('RIMAC', 'Rimac Concept 2')
    AddTextEntry('Evoque', 'Rangerover Evoque')
    AddTextEntry('SafetyCar', 'F1-SafetyCar')
    AddTextEntry('SENNAS', 'McLaren Senna')
    AddTextEntry('mcst', 'Mclaren Speedtail')
    AddTextEntry('svt00', 'Ford Mustanf ')
    AddTextEntry('subietuning', 'Subaru whatever')
    -- AddTextEntry('SULTANRSV8', '')
    AddTextEntry('vip8', 'Dodge Viper')
    AddTextEntry('c70t5r', 'Volvo C-70')
    AddTextEntry('golfmk7', 'Volkswagon Golf MK7')
    AddTextEntry('TIGUAN', 'Volkswagon Tiguan')
    AddTextEntry('VW16', 'Voldswagon Concept')
    AddTextEntry('willif1', 'F1- Williams')
    -- MOTOCYCLES
end)